import type { InferGetServerSidePropsType, GetServerSideProps } from "next";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { api } from "@/lib/axiosConfig";
import { CryptoType, CryptoTable } from "@/components";

type Latest = {
  data: CryptoType;
  status: any;
};

export default function Home({
  latest,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Dp Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CryptoTable data={latest.data} />
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  latest: Latest;
}> = async (ctx) => {
  const res = await api.get("/api/v1/cryptocurrency/listings/latest", {
    params: ctx.query,
  });

  return { props: { latest: res.data } };
};
