import type { InferGetServerSidePropsType, GetServerSideProps } from "next";

import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { api } from "@/lib/axiosConfig";

type Latest = {
  data: any[];
  status: any;
};

export default function Home({
  latest,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Dp Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{JSON.stringify(latest, null, 2)}</main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  latest: Latest;
}> = async () => {
  const res = await api.get("/api/v1/cryptocurrency/listings/latest");
  return { props: { latest: res.data } };
};
